const books = [
  {
    Grozine: [
      {
        ISBN: "IS-1111",
        year: 2017,
        name: "Grozine knyga",
        pages: 250,
        quantity: 15,
        price: "25 EUR",
      },
      {
        ISBN: "IS-1222",
        year: 2006,
        name: "Eilierasciai",
        pages: 53,
        quantity: 6,
        price: "7.99 EUR",
      },
      {
        ISBN: "IS-1333",
        year: 2022,
        name: "Grazios istorijos",
        pages: 175,
        quantity: 23,
        price: "12.50 EUR",
      },
      {
        ISBN: "IS-1444",
        year: 2021,
        name: "Meiles istorija",
        pages: 300,
        quantity: 3,
        price: "20 EUR",
      },
      {
        ISBN: "IS-1555",
        year: 2019,
        name: "Grozine literatura",
        pages: 190,
        quantity: 32,
        price: "25 EUR",
      },
    ],
    Siaubo: [
      {
        ISBN: "IS-2111",
        year: 2017,
        name: "Siaubo miskas",
        pages: 123,
        quantity: 5,
        price: "25 EUR",
      },
      {
        ISBN: "IS-2222",
        year: 2015,
        name: "Baubas",
        pages: 249,
        quantity: 9,
        price: "5.99 EUR",
      },
      {
        ISBN: "IS-2333",
        year: 2005,
        name: "Siaubo istorijos",
        pages: 86,
        quantity: 20,
        price: "3.99 EUR",
      },
      {
        ISBN: "IS-2444",
        year: 2022,
        name: "Klyksmas",
        pages: 150,
        quantity: 7,
        price: "16 EUR",
      },
      {
        ISBN: "IS-2555",
        year: 2020,
        name: "Tunas Tamsoje",
        pages: 300,
        quantity: 3,
        price: "30 EUR",
      },
    ],
    Fantastika: [
      {
        ISBN: "IS-3111",
        year: 2022,
        name: "Institucija",
        pages: 608,
        quantity: 13,
        price: "19.79 EUR",
      },
      {
        ISBN: "IS-3222",
        year: 2022,
        name: "Jai bus Kraujo",
        pages: 416,
        quantity: 5,
        price: "16.19 EUR",
      },
      {
        ISBN: "IS-3333",
        year: 2022,
        name: "Piranzeris",
        pages: 240,
        quantity: 17,
        price: "21.69 EUR",
      },
      {
        ISBN: "IS-3444",
        year: 2021,
        name: "As, Robotas",
        pages: 272,
        quantity: 5,
        price: "15.43 EUR",
      },
      {
        ISBN: "IS-3555",
        year: 2016,
        name: "Sachta",
        pages: 544,
        quantity: 14,
        price: "6.49 EUR",
      },
    ],
  },
];

export default books;

